/**
 * Auto-generated. Embedded assets for the Nexus local CLI bridge:
 * the bundled `nexus` CLI plus the agent discovery artifacts the installer
 * writes to a machine-global location.
 *
 * DO NOT EDIT MANUALLY — regenerated by scripts/generate-cli-content.mjs.
 */

/** Combined content hash — used to detect and refresh a stale on-disk install. */
export const NEXUS_CLI_ASSETS_HASH = "ff4ecbd3b850b8a8";

/** Bundled standalone `nexus` CLI (written to <dataDir>/nexus-cli.js). */
export const NEXUS_CLI_JS = `#!/usr/bin/env node
"use strict";

// cli/nexus-cli.ts
var import_node_fs3 = require("node:fs");
var import_node_path2 = require("node:path");

// cli/mcpLineClient.ts
var import_node_net = require("node:net");
function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function parseJsonRpcResponse(line) {
  let parsed;
  try {
    parsed = JSON.parse(line);
  } catch {
    return null;
  }
  if (!isRecord(parsed) || typeof parsed.id !== "number") return null;
  const response = { id: parsed.id };
  if ("result" in parsed) response.result = parsed.result;
  if ("error" in parsed) {
    if (!isRecord(parsed.error) || typeof parsed.error.code !== "number" || typeof parsed.error.message !== "string") return null;
    response.error = { code: parsed.error.code, message: parsed.error.message };
  }
  return response;
}
var McpLineClient = class {
  constructor(socketPath, opts = {}) {
    this.socketPath = socketPath;
    this.socket = null;
    this.nextId = 1;
    this.pending = /* @__PURE__ */ new Map();
    this.buffer = "";
    this.timeoutMs = opts.timeoutMs ?? 2e4;
  }
  connect() {
    return new Promise((resolve, reject) => {
      const socket = (0, import_node_net.createConnection)(this.socketPath);
      this.socket = socket;
      const onConnectError = (err) => {
        reject(new Error(
          \`Cannot connect to \${this.socketPath}: \${err.message}. Is Obsidian open with Nexus running for this vault?\`
        ));
      };
      socket.once("error", onConnectError);
      socket.once("connect", () => {
        socket.removeListener("error", onConnectError);
        socket.on("error", (err) => this.failAll(err));
        resolve();
      });
      socket.on("data", (chunk) => this.onData(chunk));
      socket.on("close", () => this.failAll(new Error("socket closed by server")));
    });
  }
  onData(chunk) {
    this.buffer += chunk.toString("utf8");
    let idx;
    while ((idx = this.buffer.indexOf("\\n")) >= 0) {
      const line = this.buffer.slice(0, idx).trim();
      this.buffer = this.buffer.slice(idx + 1);
      if (!line) continue;
      const msg = parseJsonRpcResponse(line);
      if (!msg) continue;
      if (this.pending.has(msg.id)) {
        const p = this.pending.get(msg.id);
        this.pending.delete(msg.id);
        if (msg.error) {
          p.reject(new Error(\`\${msg.error.message} (JSON-RPC code \${msg.error.code})\`));
        } else {
          p.resolve(msg.result);
        }
      }
    }
  }
  failAll(err) {
    for (const p of this.pending.values()) p.reject(err);
    this.pending.clear();
  }
  request(method, params) {
    if (!this.socket) return Promise.reject(new Error("not connected"));
    const id = this.nextId++;
    const payload = JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\\n";
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(\`Timeout after \${this.timeoutMs}ms waiting for "\${method}"\`));
      }, this.timeoutMs);
      this.pending.set(id, {
        resolve: (v) => {
          clearTimeout(timer);
          resolve(v);
        },
        reject: (e) => {
          clearTimeout(timer);
          reject(e);
        }
      });
      this.socket.write(payload);
    });
  }
  notify(method, params) {
    this.socket?.write(JSON.stringify({ jsonrpc: "2.0", method, params }) + "\\n");
  }
  async initialize() {
    const result = await this.request("initialize", {
      protocolVersion: "2025-06-18",
      capabilities: {},
      clientInfo: { name: "nexus-cli", version: "0.1.0" }
    });
    this.notify("notifications/initialized");
    return result;
  }
  listTools() {
    return this.request("tools/list", {});
  }
  callTool(name, args) {
    return this.request("tools/call", { name, arguments: args });
  }
  close() {
    this.socket?.end();
    this.socket?.destroy();
    this.socket = null;
  }
};

// cli/playbooks.ts
var import_node_fs = require("node:fs");
var import_node_os = require("node:os");
var import_node_path = require("node:path");
function playbooksDir() {
  if (process.env.NEXUS_PLAYBOOKS_DIR) return process.env.NEXUS_PLAYBOOKS_DIR;
  const home = (0, import_node_os.homedir)();
  const dataDir = process.platform === "win32" ? (0, import_node_path.join)(process.env.LOCALAPPDATA || (0, import_node_path.join)(home, "AppData", "Local"), "nexus") : (0, import_node_path.join)(home, ".local", "share", "nexus");
  return (0, import_node_path.join)(dataDir, "skill", "playbooks");
}
function parseFrontmatter(raw) {
  const m = raw.match(/^---\\r?\\n([\\s\\S]*?)\\r?\\n---\\r?\\n?([\\s\\S]*)$/);
  const meta = { name: "", intent: "", tools: [] };
  if (!m) return { meta, body: raw };
  const fm = m[1];
  const nameM = fm.match(/^name:\\s*(.+)$/m);
  if (nameM) meta.name = nameM[1].trim().replace(/^["']|["']$/g, "");
  const intentM = fm.match(/^intent:\\s*(.+)$/m);
  if (intentM) meta.intent = intentM[1].trim().replace(/^["']|["']$/g, "");
  const toolsM = fm.match(/^tools:\\s*\\[([\\s\\S]*?)\\]/m);
  if (toolsM) meta.tools = toolsM[1].split(",").map((s) => s.trim()).filter(Boolean);
  return { meta, body: m[2] };
}
function listPlaybooks(dir) {
  if (!(0, import_node_fs.existsSync)(dir)) return [];
  return (0, import_node_fs.readdirSync)(dir).filter((f) => f.endsWith(".md") && !f.startsWith("_")).map((f) => parseFrontmatter((0, import_node_fs.readFileSync)((0, import_node_path.join)(dir, f), "utf8")).meta).filter((m) => m.name);
}

// cli/commandLine.ts
function partitionUseArgv(argv) {
  if (argv[0] !== "use") return { outerArgv: argv, toolArgv: null };
  const delimiterIndex = argv.indexOf("--", 1);
  if (delimiterIndex < 0) return { outerArgv: argv, toolArgv: null };
  return {
    outerArgv: argv.slice(0, delimiterIndex),
    toolArgv: argv.slice(delimiterIndex + 1)
  };
}
function quoteToolToken(value) {
  if (/^[A-Za-z0-9_./:@%+=-]+$/.test(value)) return value;
  const escaped = value.replace(/\\\\/g, "\\\\\\\\").replace(/"/g, '\\\\"').replace(/\\n/g, "\\\\n").replace(/\\r/g, "\\\\r").replace(/\\t/g, "\\\\t");
  return \`"\${escaped}"\`;
}
function serializeToolArgv(toolArgv) {
  if (toolArgv.length < 2) {
    throw new Error("Structured \`use\` needs an agent and command after \`--\`.");
  }
  return toolArgv.map(quoteToolToken).join(" ");
}
function hydrateToolContentArgv(toolArgv, readers) {
  const stdinIndexes = [];
  const fileIndexes = [];
  const contentIndexes = [];
  toolArgv.forEach((token, index2) => {
    if (token === "--content-stdin") stdinIndexes.push(index2);
    if (token === "--content-file") fileIndexes.push(index2);
    if (token === "--content") contentIndexes.push(index2);
  });
  const transportCount = stdinIndexes.length + fileIndexes.length;
  if (transportCount === 0) return toolArgv;
  if (transportCount > 1) {
    throw new Error("Use exactly one of --content-stdin or --content-file.");
  }
  if (contentIndexes.length > 0) {
    throw new Error("Do not combine --content with --content-stdin or --content-file.");
  }
  if (stdinIndexes.length === 1) {
    const index2 = stdinIndexes[0];
    return [
      ...toolArgv.slice(0, index2),
      "--content",
      readers.readStdin(),
      ...toolArgv.slice(index2 + 1)
    ];
  }
  const index = fileIndexes[0];
  const path = toolArgv[index + 1];
  if (path === void 0 || path.startsWith("--")) {
    throw new Error("--content-file requires a local file path.");
  }
  return [
    ...toolArgv.slice(0, index),
    "--content",
    readers.readFile(path),
    ...toolArgv.slice(index + 2)
  ];
}
function resolveUseCommand(positionals, toolArgv) {
  if (toolArgv !== null) {
    if (positionals.length !== 1 || positionals[0] !== "use") {
      throw new Error("With structured \`use\`, put context flags before \`--\` and the complete tool command after it.");
    }
    return serializeToolArgv(toolArgv);
  }
  if (positionals.length < 2) {
    throw new Error("\`use\` needs a tool command after \`--\`.");
  }
  if (positionals.length > 2) {
    throw new Error(
      'The legacy tool command arrived as multiple shell arguments. PowerShell may have consumed nested double quotes. Use the structured form: nexus use --memory "..." --goal "..." -- memory load-workspace --workspace "NeuroAI Mapping".'
    );
  }
  return positionals[1];
}

// cli/vaultDiscovery.ts
var import_node_fs2 = require("node:fs");
var import_node_child_process = require("node:child_process");
var NAME_PREFIX = "nexus_mcp_";
var UNIX_SOCK_DIR = "/tmp";
var UNIX_SUFFIX = ".sock";
var WIN_PIPE_DIR = "\\\\\\\\.\\\\pipe\\\\";
var WINDOWS_PIPE_LIST_SCRIPT = "Get-ChildItem -LiteralPath '\\\\\\\\.\\\\pipe\\\\' -Name";
var SAFE_PIPE_NAME = /^nexus_mcp_[a-z0-9_-]+$/;
function parseWindowsPipeListing(output) {
  const names = output.split(/\\r?\\n/).map((line) => line.trim()).filter((line) => SAFE_PIPE_NAME.test(line));
  return [...new Set(names)].sort((left, right) => left.localeCompare(right)).map((pipeName) => ({
    name: pipeName.slice(NAME_PREFIX.length),
    path: \`\${WIN_PIPE_DIR}\${pipeName}\`
  }));
}
function listWindowsVaultPipes() {
  const result = (0, import_node_child_process.spawnSync)(
    "powershell.exe",
    ["-NoLogo", "-NoProfile", "-NonInteractive", "-Command", WINDOWS_PIPE_LIST_SCRIPT],
    {
      encoding: "utf8",
      timeout: 5e3,
      windowsHide: true
    }
  );
  if (result.error || result.status !== 0) {
    const detail = result.error?.message || String(result.stderr || "").trim() || "unknown error";
    throw new Error(
      \`Could not enumerate Windows named pipes: \${detail}. Pass --vault <name> or set NEXUS_VAULT as a fallback.\`
    );
  }
  return parseWindowsPipeListing(String(result.stdout || ""));
}
function isOwnUnixSocket(path) {
  if (typeof process.getuid !== "function") return false;
  try {
    const stat = (0, import_node_fs2.lstatSync)(path);
    return stat.isSocket() && stat.uid === process.getuid();
  } catch {
    return false;
  }
}
function listVaultSockets(platform = process.platform) {
  if (platform === "win32") {
    return listWindowsVaultPipes();
  }
  try {
    return (0, import_node_fs2.readdirSync)(UNIX_SOCK_DIR).filter((fileName) => fileName.startsWith(NAME_PREFIX) && fileName.endsWith(UNIX_SUFFIX)).map((fileName) => ({
      name: fileName.slice(NAME_PREFIX.length, -UNIX_SUFFIX.length),
      path: \`\${UNIX_SOCK_DIR}/\${fileName}\`
    })).filter((socket) => isOwnUnixSocket(socket.path));
  } catch (error) {
    const code = error.code;
    if (code === "ENOENT") return [];
    throw error;
  }
}

// cli/nexus-cli.ts
var IS_WIN = process.platform === "win32";
function sanitizeVaultName(name) {
  if (!name) return "";
  return name.toLowerCase().replace(/[^\\w\\s-]/g, "").replace(/\\s+/g, "-").replace(/-+/g, "-");
}
function vaultSocketPath(sanitized) {
  return IS_WIN ? \`\${WIN_PIPE_DIR}\${NAME_PREFIX}\${sanitized}\` : \`\${UNIX_SOCK_DIR}/\${NAME_PREFIX}\${sanitized}\${UNIX_SUFFIX}\`;
}
function resolveVault(requested) {
  const want = requested ?? process.env.NEXUS_VAULT ?? void 0;
  if (want) {
    const s = sanitizeVaultName(want);
    const p = vaultSocketPath(s);
    if (!IS_WIN && (0, import_node_fs3.existsSync)(p) && !isOwnUnixSocket(p)) {
      throw new Error(\`Refusing to connect: \${p} is not owned by the current user.\`);
    }
    return { name: s, path: p };
  }
  const sockets = listVaultSockets();
  if (sockets.length === 1) return sockets[0];
  if (sockets.length === 0) {
    throw new Error("No open Nexus vaults found. Is Obsidian running with Nexus? Or pass --vault <name>.");
  }
  throw new Error(\`Multiple vaults open: \${sockets.map((x) => x.name).join(", ")}. Pass --vault <name>.\`);
}
function parseArgs(argv) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next !== void 0 && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else {
      positionals.push(a);
    }
  }
  return { positionals, flags };
}
function printToolResult(result, asJson) {
  if (asJson) {
    process.stdout.write(JSON.stringify(result, null, 2) + "\\n");
    return result.isError ? 1 : 0;
  }
  const text = (result.content ?? []).filter((c) => c.type === "text" && typeof c.text === "string").map((c) => c.text).join("\\n");
  const out = text || JSON.stringify(result, null, 2);
  if (result.isError) {
    process.stderr.write(out + "\\n");
    return 1;
  }
  process.stdout.write(out + "\\n");
  return 0;
}
function buildUsage() {
  let playbookLines;
  try {
    const books = listPlaybooks(playbooksDir());
    playbookLines = books.length ? books.map((b) => \`    \${b.name.padEnd(11)}\${b.intent}\`).join("\\n") : "    (none installed \\u2014 re-run the Nexus CLI installer)";
  } catch {
    playbookLines = "    (run \`nexus playbook\` to list)";
  }
  return \`nexus \\u2014 drive a running Nexus (Obsidian) vault from the shell (no MCP config)

Two verbs: DISCOVER what you can do, then EXECUTE. Discovery returns schemas, never
vault content \\u2014 don't loop it hunting for data. Search/list return LOCATIONS; read
before you act. You cannot escape the vault (no ../~/absolute paths).

COMMANDS
  nexus tools [selector...]          DISCOVER \\u2014 tool schemas (getTools). Drill down:
                                       nexus tools                   all agents (catalog)
                                       nexus tools storage           one agent's tools
                                       nexus tools storage list      one tool, full arg schema
                                       nexus tools "storage list, content read"   several
  nexus use [context] -- <command>    EXECUTE a tool (useTools). See CONTEXT below.
  nexus playbook [name]              Task primer: recipe + your workspaces + preloaded
                                     tools, in one call. \\\`nexus playbook\\\` lists them.
  nexus vaults                       List open Nexus vaults (live sockets)
  nexus doctor [--vault <name>]      Connect + handshake; print server info
  nexus --help                       This manual

CONTEXT (flags on \\\`use\\\`; \\\`tools\\\` accepts them too. \\\`playbook\\\` reads only
         --workspace/--session/--vault and fills memory/goal for you)
  --memory "<text>"       REQUIRED \\u2014 rolling summary of what you've done/learned
  --goal "<text>"         REQUIRED \\u2014 this call's objective, one sentence
                          (empty or placeholder like "N/A" is REJECTED with a steer)
  --workspace <id>        scope for traces/memory (default: "default")
  --session <name>        continuity across calls (default: "nexus-cli"; keep it stable)
  --constraints "<text>"  optional guardrails
  --vault <name>          target a vault (else: the single open one, or $NEXUS_VAULT)
  --json                  print the raw JSON result
  --dry-run               print the reconstructed request; do not connect or execute

CONTENT INPUT (CLI-only flags after the \\\`--\\\` delimiter)
  --content-stdin         read the tool's --content value from standard input
  --content-file <path>   read the tool's --content value from a local file
                          (use one transport flag; do not also pass --content)

CLI SYNTAX
  \\u2022 Canonical form: context flags first, then \\\`--\\\`, then one tool command as normal
    shell arguments. Commands are kebab-case (content set-property, memory load-workspace).
    Multiword values need only one shell quote layer: --workspace "NeuroAI Mapping".
  \\u2022 The legacy one-string form remains supported. On Windows PowerShell, nested double
    quotes can be consumed before Node receives them; prefer the canonical \\\`--\\\` form.
  \\u2022 For multiline Markdown or text containing embedded quotes, keep the payload out of
    shell argv: \\\`Get-Content -Raw note.md | nexus use ... -- content write --path X.md --content-stdin\\\`,
    or pass \\\`--content-file note.md\\\`.
  \\u2022 Paths are vault-relative. "..", "~", absolute paths are rejected; a leading "/" is
    stripped. You cannot read or write outside the vault.
  \\u2022 Arrays: --tags "[work, urgent]". Wikilinks keep brackets: --links "[[[A]], [[B]]]".
  \\u2022 content replace is pattern-anchored {path, start, end, content} \\u2014 start/end are
    exact ANCHOR TEXT from the note, not line numbers. Read the note first. (insert
    handles append/prepend.)

GOTCHAS
  \\u2022 \\\`nexus tools\\\` returns schemas, not data \\u2014 never loop it for content.
  \\u2022 Search/list return locations (path + score) \\u2014 follow every hit with \\\`content read\\\`.
  \\u2022 \\\`content read\\\` requires a start line: content read --path X --start-line 1 (1 = top).
  \\u2022 ALL flags are kebab-case \\u2014 camelCase (e.g. --newPath, --activeTask) is rejected as
    an unknown flag; use --new-path, --active-task. Get exact flags from \\\`nexus tools <tool>\\\`.
  \\u2022 Context fields (--workspace/--session/--memory/--goal) go before \\\`--\\\`, never
    after it \\u2014 e.g. --workspace-id inside the tool command is rejected.
  \\u2022 --memory/--goal are enforced \\u2014 send real values or the call is rejected.
  \\u2022 Media generation is async \\u2014 \\\`prompt generate-*\\\` returns a job; poll
    \\\`prompt check-generated-artifact\\\`.
  \\u2022 States: the AI gets archive (reversible), not delete.
  \\u2022 No open vault \\u2192 the socket is absent; open Obsidian with Nexus. Multiple open \\u2192
    pass --vault <name>.

TOOL CATALOG
  Core agents (always on): content, storage, search, canvas, task, memory, prompt, ingest.
  Apps (opt-in, per vault): composer, data, elevenlabs, skills, web \\u2014 appear only when
  enabled. The live, authoritative catalog for THIS vault is always: nexus tools

PLAYBOOKS  (nexus playbook <name>)
\${playbookLines}

EXAMPLES
  nexus tools "content read, search content"
  nexus use --memory "auditing notes" --goal "read today's daily" -- content read --path Daily/2026-07-17.md --start-line 1
  nexus use --vault "My Notes" --memory "smoke test" --goal "list vault root" -- storage list
  nexus use --dry-run --memory "resuming research" --goal "load workspace" -- memory load-workspace --workspace "NeuroAI Mapping" --limit 1
  nexus playbook vault-work
\`;
}
async function withClient(vaultName, fn) {
  const vault = resolveVault(vaultName);
  const client = new McpLineClient(vault.path);
  await client.connect();
  try {
    await client.initialize();
    return await fn(client);
  } finally {
    client.close();
  }
}
async function main() {
  const argv = process.argv.slice(2);
  const { outerArgv, toolArgv } = partitionUseArgv(argv);
  const { positionals, flags } = parseArgs(outerArgv);
  const cmd = positionals[0];
  const asJson = flags.json === true;
  const vaultFlag = typeof flags.vault === "string" ? flags.vault : void 0;
  if (!cmd || cmd === "help" || flags.help === true) {
    process.stdout.write(buildUsage());
    return 0;
  }
  if (cmd === "vaults") {
    const sockets = listVaultSockets();
    if (sockets.length === 0) {
      process.stdout.write("No open Nexus vaults. Is Obsidian running with Nexus enabled?\\n");
      return 0;
    }
    for (const s of sockets) process.stdout.write(\`\${s.name}	\${s.path}
\`);
    return 0;
  }
  if (cmd === "doctor") {
    return withClient(vaultFlag, async (client) => {
      const tools = await client.listTools();
      process.stdout.write("OK \\u2014 connected, handshaked, tools/list responded.\\n");
      process.stdout.write(JSON.stringify(tools, null, 2) + "\\n");
      return 0;
    });
  }
  if (cmd === "tools") {
    const selector = positionals.slice(1).join(" ") || "--help";
    return withClient(vaultFlag, async (client) => {
      const result = await client.callTool("toolManager_getTools", {
        tool: selector,
        workspaceId: typeof flags.workspace === "string" ? flags.workspace : "default",
        sessionId: typeof flags.session === "string" ? flags.session : "nexus-cli",
        memory: typeof flags.memory === "string" ? flags.memory : "Discovering available Nexus tools.",
        goal: typeof flags.goal === "string" ? flags.goal : \`Inspect "\${selector}" tools.\`
      });
      return printToolResult(result, asJson);
    });
  }
  if (cmd === "playbook") {
    const dir = playbooksDir();
    const name = positionals[1];
    if (!name) {
      const books = listPlaybooks(dir);
      if (books.length === 0) {
        process.stderr.write(\`No playbooks installed (looked in \${dir}). Re-run the Nexus CLI installer, or set NEXUS_PLAYBOOKS_DIR.
\`);
        return 1;
      }
      process.stdout.write("Nexus playbooks \\u2014 task primers. Run \`nexus playbook <name>\`:\\n\\n");
      const pad = Math.max(...books.map((b) => b.name.length));
      for (const b of books) process.stdout.write(\`  \${b.name.padEnd(pad)}  \${b.intent}
\`);
      process.stdout.write("\\nEach emits: the shared spine, your workspaces, the recipe, and the tools it needs (preloaded).\\n");
      return 0;
    }
    if (name.includes("/") || name.includes("\\\\") || name.includes("..") || name.startsWith(".")) {
      process.stderr.write(\`Invalid playbook name "\${name}". Use a plain name \\u2014 run \\\`nexus playbook\\\` to list.
\`);
      return 2;
    }
    const file = (0, import_node_path2.join)(dir, \`\${name}.md\`);
    if (!(0, import_node_fs3.existsSync)(file)) {
      const books = listPlaybooks(dir);
      const names = books.map((b) => b.name).join(", ") || "(none installed)";
      process.stderr.write(\`Unknown playbook "\${name}". Available: \${names}. Run \\\`nexus playbook\\\` to list.
\`);
      return 2;
    }
    const { meta, body } = parseFrontmatter((0, import_node_fs3.readFileSync)(file, "utf8"));
    const preamblePath = (0, import_node_path2.join)(dir, "_preamble.md");
    const preamble = (0, import_node_fs3.existsSync)(preamblePath) ? (0, import_node_fs3.readFileSync)(preamblePath, "utf8").trim() : "";
    if (preamble) process.stdout.write(preamble + "\\n\\n");
    const ctx = {
      workspaceId: typeof flags.workspace === "string" ? flags.workspace : "default",
      sessionId: typeof flags.session === "string" ? flags.session : "nexus-cli",
      memory: \`Loading the "\${name}" playbook.\`,
      goal: \`Prepare to run the \${name} task.\`
    };
    try {
      const { workspaces, tools } = await withClient(vaultFlag, async (client) => {
        const ws = await client.callTool("toolManager_useTools", { ...ctx, tool: "memory list-workspaces" });
        let tl = null;
        if (meta.tools.length) {
          tl = await client.callTool("toolManager_getTools", { ...ctx, tool: meta.tools.join(", ") });
        }
        return { workspaces: ws, tools: tl };
      });
      process.stdout.write("## Your workspaces\\n\\nPick one to load as step 1 (or create a new one):\\n\\n");
      printToolResult(workspaces, false);
      process.stdout.write("\\n---\\n\\n" + body.trim() + "\\n");
      if (tools) {
        process.stdout.write("\\n## Preloaded tool schemas\\n\\n");
        printToolResult(tools, false);
      }
    } catch (err) {
      process.stdout.write(\`## Your workspaces

_(no reachable vault: \${err.message} \\u2014 run \\\`nexus vaults\\\`, then load one as step 1.)_

\`);
      process.stdout.write("---\\n\\n" + body.trim() + "\\n");
      if (meta.tools.length) {
        process.stdout.write(\`
## Tools for this task

Once a vault is open, preload them with:
  nexus tools "\${meta.tools.join(", ")}"
\`);
      }
    }
    return 0;
  }
  if (cmd === "use") {
    let command;
    try {
      const hydratedToolArgv = toolArgv === null ? null : hydrateToolContentArgv(toolArgv, {
        readStdin: () => {
          if (process.stdin.isTTY) {
            throw new Error("--content-stdin requires piped or redirected standard input.");
          }
          return (0, import_node_fs3.readFileSync)(0, "utf8");
        },
        readFile: (path) => (0, import_node_fs3.readFileSync)(path, "utf8")
      });
      command = resolveUseCommand(positionals, hydratedToolArgv);
    } catch (error) {
      process.stderr.write(\`Error: \${error.message}
\`);
      return 2;
    }
    const memory = typeof flags.memory === "string" ? flags.memory : "";
    const goal = typeof flags.goal === "string" ? flags.goal : "";
    if (!memory || !goal) {
      process.stderr.write("Error: --memory and --goal are REQUIRED (Nexus context contract).\\n");
      return 2;
    }
    const args = {
      tool: command,
      workspaceId: typeof flags.workspace === "string" ? flags.workspace : "default",
      sessionId: typeof flags.session === "string" ? flags.session : "nexus-cli",
      memory,
      goal
    };
    if (typeof flags.constraints === "string") args.constraints = flags.constraints;
    if (flags["dry-run"] === true) {
      process.stdout.write("DRY RUN \\u2014 no vault connection and no tool execution.\\n");
      process.stdout.write(JSON.stringify(args, null, 2) + "\\n");
      return 0;
    }
    return withClient(vaultFlag, async (client) => {
      const result = await client.callTool("toolManager_useTools", args);
      return printToolResult(result, asJson);
    });
  }
  process.stderr.write(\`Unknown command "\${cmd}". Run \\\`nexus --help\\\`.
\`);
  return 2;
}
main().then((code) => process.exit(code)).catch((err) => {
  process.stderr.write(\`nexus: \${err.message}
\`);
  process.exit(1);
});
`;

/** SKILL.md for Claude Code (written to <dataDir>/skill/SKILL.md). */
export const NEXUS_SKILL_MD = `---
name: nexus
description: >-
  Read, search, and edit the user's Obsidian vault (notes, folders, canvas,
  tasks, memory/workspaces, saved prompts) from the shell via the \`nexus\` CLI —
  no MCP connection needed. Use whenever the user refers to their vault, notes,
  daily notes, second brain, or Obsidian, or asks you to find/read/change
  something stored there and the \`nexus\` command is on PATH. Do not use it to
  edit files in the current code repository; use normal file tools for those.
---

# Nexus vault CLI

\`nexus\` drives a running Nexus (Obsidian) vault from the shell over a local
socket — no MCP config. It has two verbs: **discover** what you can do, then
**execute**.

## Start here

**Run \`nexus --help\` first.** It is the authoritative, always-current manual —
commands, the context contract, CLI syntax, gotchas, and the tool catalog. It's
offline and instant (no socket), so read it before your first real command
instead of guessing.

For a common task, **\`nexus playbook <name>\`** gives you a ready-to-run recipe
*plus* your workspaces and the exact tools it needs, in one call. Run
\`nexus playbook\` to see what's available (typically: \`vault-work\`, \`organize\`,
\`tasks\`, \`prompt\`).

## The mindset (this is what \`--help\` can't teach you)

- **Explore → inspect → exploit.** Search/list find *locations*; \`content read\`
  gets *contents*; then you write. A search hit is a \`{path, score}\`, **not** the
  note — never quote, summarize, or edit from a hit without reading it first.
- **\`nexus tools\` returns schemas, not data.** It's discovery. Don't loop it
  hoping for vault content — that comes from \`nexus use --memory … --goal … -- content read …\`.
- **\`--memory\` and \`--goal\` are real and enforced.** You're operating a person's
  live vault; pass a genuine running summary and objective, not placeholders.
- **You can't escape the vault.** Paths are vault-relative; \`..\`, \`~\`, and
  absolute paths are rejected. That's a guardrail, not a bug.
- **Nothing is destroyed.** The AI gets archive (reversible), not delete.
- **Windows:** \`nexus vaults\` discovers local named pipes. If policy blocks
  enumeration, pass \`--vault <name>\` or set \`NEXUS_VAULT\`.

## The shape

\`\`\`
nexus tools [selector]              # discover — tool schemas (never vault data)
nexus use --memory "<what you're doing>" --goal "<objective>" -- \\
    <agent command --flags>         # execute — runs one tool, prints the result
\`\`\`

The \`--\` delimiter is canonical: context belongs before it; the tool command
belongs after it. This avoids nested command-string quoting, especially in
Windows PowerShell. The legacy one-string form remains supported.

For multiline Markdown or content containing embedded quotes, keep the body
out of shell argv. Pipe it with \`--content-stdin\` or pass a local path with
\`--content-file\`; put either flag after the \`--\` delimiter and do not also pass
\`--content\`:

\`\`\`powershell
Get-Content -Raw .\\note.md |
    nexus use --memory "importing note" --goal "write note" -- content write --path Notes/Imported.md --content-stdin
\`\`\`

Everything else — the flag table, per-tool schemas, syntax rules, the live
per-vault catalog (including any enabled app agents) — comes from \`nexus --help\`,
\`nexus tools <tool>\`, and \`nexus playbook <name>\`. Prefer those over guessing;
they're always current.
`;

/** AGENTS.md pointer block for Codex / skill-less agents. */
export const NEXUS_AGENTS_MD = `## Nexus vault access

This machine runs Nexus (Obsidian). To read, search, or edit the user's vault —
notes, folders, canvas, tasks, memory/workspaces, saved prompts — use the
\`nexus\` CLI. No MCP connection is needed.

**Run \`nexus --help\` first.** It's the authoritative, always-current manual
(commands, the required context contract, CLI syntax, gotchas, tool catalog) —
offline and instant, so read it before your first command instead of guessing.

- **Discover:** \`nexus tools [selector]\` returns tool schemas (not vault data).
  Drill down: \`nexus tools storage list\` = one tool's full arg schema.
- **Execute:** \`nexus use --memory "<what you're doing>" --goal "<objective>" -- <agent command --flags>\`.
  \`--memory\`/\`--goal\` are **required** on every \`use\`.
- **Multiline content:** keep Markdown/YAML and embedded quotes out of shell
  argv. After \`--\`, use \`--content-stdin\` with piped input or
  \`--content-file <local-path>\` instead of \`--content\`.
- **Task recipes:** \`nexus playbook <name>\` emits a ready-to-run recipe plus your
  workspaces and preloaded tools in one call (\`nexus playbook\` lists them).
- Search/list results are **locations, not contents** — follow a hit with
  \`content read --path <path> --start-line 1\` (read requires a start line).
  \`nexus tools\` returns schemas, never data.
- One open vault is used automatically; if several are open, run \`nexus vaults\`
  and pass \`--vault <name>\` (or set \`NEXUS_VAULT\`). If Windows policy blocks
  named-pipe enumeration, direct \`--vault <name>\` connections still work.

This applies to the user's Obsidian vault, not files in the current code
repository — use normal file tools for those.
`;

/** Playbook markdown by filename (written to <dataDir>/skill/playbooks/). */
export const NEXUS_PLAYBOOKS: Record<string, string> = {
    "_preamble.md": `# Nexus playbook

This is a task primer. Below, in order, you get: **this spine**, **your
workspaces**, the **recipe**, and the **tools it needs (already discovered)** —
so you can go straight to \`nexus use\` without a separate \`nexus tools\` call.

**Every playbook starts the same way:**

1. **Pick a workspace and load it.** Choose from *Your workspaces* below and run
   \`nexus use --memory … --goal … -- memory load-workspace --workspace "<name>"\`. If
   none fits, create one with \`memory create-workspace\`. Loading scopes your traces
   and auto-loads that workspace's task summary. (This playbook only *lists*
   workspaces — loading is your call, since only you know which one.)
2. **Thread the workspace** into every following call with \`--workspace <name>\`
   (the outer context flag), and keep a stable \`--session <name>\` for the task.
3. **Always pass real \`--memory\` and \`--goal\`** — a running summary and the
   current objective. Placeholders are rejected.
4. **Checkpoint at milestones** with \`memory create-state\` so the work is
   restorable (archive is reversible; there is no destructive delete). It needs a
   few flags — \`--name\`, \`--conversation-context\`, \`--active-task\`, \`--active-files\`
   (array), \`--next-steps\` (array); run \`nexus tools memory create-state\` for the
   full schema.

Paths are vault-relative and confined — no \`..\`, \`~\`, or absolute escapes. **All
flags are kebab-case** — camelCase (e.g. \`--activeTask\`) is rejected as an unknown
flag; use \`--active-task\`.

For multiline Markdown/YAML or embedded quotes, keep content out of shell argv:
after \`--\`, pipe with \`--content-stdin\` or pass \`--content-file <local-path>\`
instead of \`--content\`.
`,
    "organize.md": `---
name: organize
intent: Restructure the vault — map what's there, then move / archive / create folders to tidy it
tools: [storage list, storage create-folder, storage move, storage copy, storage archive, search query-notes, search directory, memory list-workspaces, memory create-state]
---

# Playbook: organize

Reshape vault structure: **map → plan → move/archive**. Use it for "file these
notes into folders," "archive last year's dailies," "split this folder," etc.
Unlike \`vault-work\` (which edits note *bodies*), this moves and files whole notes.

## Protocol

1. **Load a workspace** (see the spine above); thread \`--workspace\`/\`--session\`.
2. **Map the current layout before touching anything.**
   - \`storage list --path "<folder>"\` — see what's in a folder.
   - \`search query-notes --sql "…"\` — query frontmatter as a database to *find*
     what to move (e.g. all notes with \`status: archived\`, or created before a
     date). Read-only SELECT; run with \`--describe\` first to see the columns.
   - \`search directory --query "<name>"\` — locate notes/folders by name.
3. **Plan the moves** — decide target folders. Create any missing folder first
   with \`storage create-folder --path "<folder>"\`.
4. **Execute, one file at a time**, verifying each result:
   - \`storage move --path <src> --new-path <dst>\` — relocate/rename (both paths
     validated; target's parent folder must exist).
   - \`storage copy --path <src> --new-path <dst>\` — duplicate instead of move.
   - \`storage archive --path <path>\` — soft-remove (reversible), for retiring a
     note without deleting it.
5. **Checkpoint** with \`memory create-state\` after a batch, so a bad reshuffle is
   restorable.

## Worked example — archive old daily notes into a subfolder

\`\`\`
# 1. load the workspace
nexus use \\
  --memory "tidying old dailies" --goal "load the journal workspace" \\
  --session tidy-dailies \\
  -- memory load-workspace --workspace journal

# 2. map — which dailies are from 2025? (query frontmatter; --describe to see columns first)
nexus use \\
  --workspace journal --session tidy-dailies \\
  --memory "finding 2025 dailies to archive" --goal "list 2025 daily notes" \\
  -- search query-notes --sql "SELECT path FROM notes WHERE path LIKE 'Daily/2025-%' ORDER BY path"

# 3. make the destination folder
nexus use \\
  --workspace journal --session tidy-dailies \\
  --memory "have the 2025 list; creating archive folder" --goal "create Daily/Archive/2025" \\
  -- storage create-folder --path Daily/Archive/2025

# 4. move each note (one call per file — verify each)
nexus use \\
  --workspace journal --session tidy-dailies \\
  --memory "moving 2025 dailies into the archive folder" --goal "move 2025-01-03.md" \\
  -- storage move --path Daily/2025-01-03.md --new-path Daily/Archive/2025/2025-01-03.md

# 5. checkpoint after the batch
nexus use \\
  --workspace journal --session tidy-dailies \\
  --memory "2025 dailies archived" --goal "checkpoint the reorg" \\
  -- memory create-state --name dailies-archived \\
  --conversation-context "moved all 2025 daily notes into Daily/Archive/2025" \\
  --active-task "archive old dailies" \\
  --active-files "[Daily/Archive/2025]" \\
  --next-steps "[do the same for 2024]"
\`\`\`

## Pitfalls

- **Moving before the target folder exists** — \`storage move\`'s target parent
  must exist; \`create-folder\` it first.
- **Bulk-moving blind** — map with \`list\`/\`query-notes\` first; one \`move\` per
  file so a failure is isolated, not a half-done sweep.
- **\`archive\` ≠ delete** — it's the reversible soft-remove; there is no
  destructive delete for the agent. That's a feature — prefer it.
- **\`query-notes\` is read-only** — it finds notes; it never changes them. Use its
  output as the move list.
- **Paths are vault-relative and confined** — no \`..\`/\`~\`/absolute on either
  \`--path\` or \`--new-path\`.
`,
    "prompt.md": `---
name: prompt
intent: Run a prompt (text or image) over your notes — inline or from your saved library — and optionally write the result back
tools: [prompt execute, prompt list, prompt get, prompt create, prompt list-models, prompt check-generated-artifact, content read, content write, memory list-workspaces, memory create-state]
---

# Playbook: prompt

Run an LLM (or image model) over vault content with \`prompt execute\`. Use it to
summarize/rewrite/extract across notes, draft new notes, or generate an image —
driving the prompt **inline** (one you write) or from a **saved prompt** in the
vault's prompt library, with **notes attached as context**, and optionally
**writing the result straight back** into a note.

## The \`prompt execute\` shape

\`prompt execute\` takes **\`--prompts\`, a JSON array** of one or more request
objects (it's a batch tool). The fields that matter:

| Field | Purpose |
|-------|---------|
| \`type\` | \`"text"\` (LLM) or \`"image"\` (image model). **Required.** |
| \`prompt\` | the prompt text — **an inline prompt you write.** Required. (For a saved prompt, still give a \`prompt\`, or a short instruction; \`customPrompt\` supplies the template.) |
| \`customPrompt\` | **name or ID of a saved prompt** (from \`prompt list\`) to use as the template. |
| \`contextFiles\` | array of **vault-relative note paths to attach as context** (text requests). |
| \`workspace\` | workspace name — gather its context automatically (text requests). |
| \`provider\` / \`model\` | pick the model (see \`prompt list-models\`); defaults to your configured agent model. |
| \`action\` | write the result back: \`{type: create\\|append\\|prepend\\|replace\\|findReplace, targetPath, start, end, …}\`. |
| \`savePath\` / \`aspectRatio\` / \`referenceImages\` | image requests only. |
| \`sequence\` / \`parallelGroup\` / \`includePreviousResults\` / \`contextFromSteps\` | chain multiple requests. |

Full live schema: \`nexus tools prompt execute\`. Saved prompts: \`prompt list\`
(names/IDs) → \`prompt get --id <name>\` to inspect one; \`prompt create\` to add one.

## Protocol

1. **Load a workspace** (see the spine above); thread \`--workspace\`/\`--session\`.
2. **Pick the driver**: write an **inline** \`prompt\`, or find a **saved** one with
   \`prompt list\` and pass its name as \`customPrompt\`.
3. **Attach the notes** the prompt should see via \`contextFiles\` (read them first
   if you need to confirm paths).
4. **Choose where the result goes**: omit \`action\` to get it on stdout (use
   \`--json\`), or set \`action\` to write it into a note.
5. **Run** \`prompt execute --prompts '[ … ]'\`. For images/audio/video it returns a
   job — poll \`prompt check-generated-artifact\`.
6. **Checkpoint** with \`memory create-state\`.

## Quoting the JSON

The \`--prompts\` value is JSON, so it carries literal double-quotes. Put it after
the structured \`--\` delimiter as one argument:

- Bash/zsh: single-quote the compact JSON normally: \`'[{"type":"text",…}]'\`.
- Windows PowerShell: native argument marshalling needs each literal JSON quote
  tripled inside the single-quoted value: \`'[{"""type""":"""text""",…}]'\`.

Use top-level \`--dry-run\` to inspect the reconstructed \`tool\` string without
connecting or executing. If quoting fights you, use a saved \`customPrompt\` so
the inline JSON stays small.

## Worked examples

**A — inline prompt, one note as context, result to stdout:**

\`\`\`
nexus use \\
  --json --workspace research --session prompt-run \\
  --memory "summarizing the auth flow note" --goal "get a 3-bullet summary" \\
  -- prompt execute --prompts '[{"type":"text","prompt":"Summarize this note in 3 bullets","contextFiles":["Projects/Auth/flow.md"]}]'
\`\`\`

**B — saved prompt + note context, write the result back into a note:**

\`\`\`
# find the saved prompt's name
nexus use --workspace research --session prompt-run \\
  --memory "looking for my weekly-review prompt" --goal "list saved prompts" \\
  -- prompt list

# run it over this week's notes and append the output to the review note
nexus use \\
  --workspace research --session prompt-run \\
  --memory "have the daily notes; running weekly-review" --goal "append a weekly review" \\
  -- prompt execute --prompts '[{"type":"text","customPrompt":"weekly-review","contextFiles":["Daily/2026-07-14.md","Daily/2026-07-15.md"],"action":{"type":"append","targetPath":"Reviews/2026-W29.md"}}]'
\`\`\`

**C — image, saved to the vault:**

\`\`\`
nexus use \\
  --workspace research --session prompt-run \\
  --memory "need a logo asset" --goal "generate a logo image" \\
  -- prompt execute --prompts '[{"type":"image","prompt":"a minimalist logo, teal on white","savePath":"Assets/logo.png","aspectRatio":"1:1"}]'
# then poll:
nexus use --workspace research --session prompt-run \\
  --memory "waiting on the logo" --goal "check image generation status" \\
  -- prompt check-generated-artifact --id <job-id>
\`\`\`

## Pitfalls

- **Forgetting \`type\`/\`prompt\`** — both are required on every item.
- **JSON quoting** — use ordinary compact JSON in Bash/zsh; triple each literal
  \`"\` for Windows PowerShell as shown above. Confirm with \`--dry-run\`; prefer
  \`customPrompt\` for anything reusable.
- **\`contextFiles\` are vault-relative** — the same confinement as everywhere;
  no \`..\`/absolute.
- **A bad \`model\`/\`provider\`** — check \`prompt list-models\` first.
- **Media is async** — \`type: image\`/\`generate-*\` returns a job; poll
  \`prompt check-generated-artifact\`, don't expect the bytes inline.
- **\`action\` overwrites** — \`replace\` needs anchor text (\`start\`/\`end\`); \`create\`
  refuses to clobber; append/prepend are safe additive writes.
`,
    "tasks.md": `---
name: tasks
intent: Run projects and tasks with dependencies — create, list, update, and wire up a task DAG
tools: [task create-project, task list-projects, task create, task list, task query, task update, task move, task link-note, memory list-workspaces, memory create-state]
---

# Playbook: tasks

Workspace-scoped project/task management with a dependency DAG. Use it for "start
a project," "add these tasks and their dependencies," "what's unblocked," "mark X
done." Tasks live **inside a workspace, under a project** — so the flow is: load
the workspace, get or create a project (capture its \`projectId\`), then add tasks.

## The one thing to get right: workspace vs project

- **Workspace** comes from the **top-level \`--workspace <name-or-id>\` context
  flag** — the same flag you pass on every call, set to the workspace you loaded.
  Task tools read their workspace scope from it automatically. **Do not** put
  \`--workspace-id\` *inside* the tool string — it's a reserved context field and
  is rejected there.
- **Project** is identified by a **\`projectId\`** that \`task create-project\` (or
  \`task list-projects\`) returns. Capture it and pass it to task calls as
  \`--project-id\`.

So: load the workspace → thread \`--workspace\` on every call → create/find a
project → capture its \`projectId\` → create tasks with \`--project-id\`.

## Protocol

1. **Load the workspace** (spine above); thread \`--workspace <name-or-id>\` on
   every following call.
2. **Get a project.** \`task list-projects\` (scoped by \`--workspace\`) to find one,
   or \`task create-project --name "<name>"\` — note the **projectId** it returns.
3. **Add tasks.** \`task create --project-id <projectId> --title "<title>"\` (add
   \`--description\`, dependencies, etc. — see \`nexus tools task create\`).
4. **Wire dependencies / reorganize.** \`task move\` to reparent or reorder in the
   DAG; \`task link-note --note-path <path>\` to attach a note to a task.
5. **Track.** \`task list\` / \`task query\` to see status, what's blocked vs
   unblocked.
6. **Update.** \`task update\` to change status/fields. \`task archive-project\` when
   a project is done (reversible).
7. **Checkpoint** with \`memory create-state\` at milestones.

## Worked example — new project, two tasks, one depends on the other

\`\`\`
# 1. load the workspace — thread --workspace (name or id) on every later call
nexus use \\
  --memory "planning the launch" --goal "load the product workspace" \\
  --session launch-plan \\
  -- memory load-workspace --workspace product

# 2. create a project — workspace comes from --workspace; capture the projectId
nexus use \\
  --workspace product --session launch-plan \\
  --memory "starting the Q3 launch project" --goal "create the Q3 Launch project" \\
  -- task create-project --name "Q3 Launch"
# → result includes the projectId, e.g. "proj_def456"

# 3. add tasks under that project
nexus use \\
  --workspace product --session launch-plan \\
  --memory "adding launch tasks" --goal "create the copy task" \\
  -- task create --project-id proj_def456 --title "Write launch copy"

nexus use \\
  --workspace product --session launch-plan \\
  --memory "adding the dependent task" --goal "create the publish task" \\
  -- task create --project-id proj_def456 --title "Publish blog post"

# 4. see the board (statuses, what's blocked)
nexus use \\
  --workspace product --session launch-plan \\
  --memory "reviewing the launch tasks" --goal "list tasks in the project" \\
  -- task list --project-id proj_def456

# 5. checkpoint
nexus use \\
  --workspace product --session launch-plan \\
  --memory "project + tasks created" --goal "checkpoint the setup" \\
  -- memory create-state --name launch-tasks-seeded \\
  --conversation-context "created Q3 Launch project with copy + publish tasks" \\
  --active-task "set up the launch project" \\
  --active-files "[]" \\
  --next-steps "[wire publish to depend on copy, assign owners]"
\`\`\`

Run \`nexus tools task create\` / \`task move\` / \`task update\` for the exact fields
(dependencies, status enum, ordering) — they carry more options than shown here.

## Pitfalls

- **Putting \`--workspace-id\` inside the tool string** — rejected as a reserved
  context field. Scope task tools with the top-level \`--workspace <name-or-id>\`
  flag instead (the workspace you loaded); it accepts a name *or* an id.
- **Creating tasks with no project** — \`task create\` needs \`--project-id\`; make or
  find the project first and capture the id it returns.
- **\`task link-note\` needs a real \`--note-path\`** — a vault-relative path to an
  existing note (same confinement rules).
- **Losing the projectId** — capture it from \`create-project\`/\`list-projects\`; the
  task calls need it. (Use \`--json\` if you need to parse it out.)
- **\`archive-project\` is reversible** — it's the retire action, not a delete.
`,
    "vault-work.md": `---
name: vault-work
intent: Search the vault, read what you find, then create or edit notes — the typical loop
tools: [search content, search directory, content read, content write, content replace, content insert, content set-property, storage list, memory list-workspaces, memory create-state]
---

# Playbook: vault-work

The 80% loop: **find → read → change.** Use it for "find the note about X and
update it," "answer a question from my notes," "add a section to Y," etc.

## Protocol

1. **Load a workspace** (see the spine above), thread \`--workspace\`/\`--session\`.
2. **Find the note(s).** Pick the search that fits:
   - \`search content --query "<terms>"\` — semantic/keyword over note bodies.
   - \`search directory --query "<name>" --paths "<folder>"\` — by filename/path.
   - \`storage list --path "<folder>"\` — browse a known folder.
   Each returns **locations** (\`path\` + score), not contents.
3. **Read before you act.** \`content read --path <path> --start-line 1\` on the
   hit(s) — \`content read\` **requires a start line** (use \`1\` to read from the
   top). Never quote, summarize, or edit from a search result alone — it has no body.
4. **Make the change** with the narrowest tool:
   - \`content set-property\` — a frontmatter field.
   - \`content insert\` — add a section (append/prepend/at an anchor).
   - \`content replace\` — a surgical edit. It is **pattern-anchored**:
     \`{path, start, end, content}\` where \`start\`/\`end\` are exact **anchor text**
     from the note (not line numbers). Read first to copy the anchors.
   - \`content write\` — a new note, or a full overwrite.
5. **Checkpoint** with \`memory create-state\` when the edit is done.

## Worked example — add a summary under a heading

\`\`\`
# 1. load the workspace you picked from the list above (--workspace = name or id)
nexus use \\
  --memory "starting: summarize the auth notes" --goal "load the research workspace" \\
  --session auth-summary \\
  -- memory load-workspace --workspace research

# 2. find
nexus use \\
  --workspace research --session auth-summary \\
  --memory "looking for the main auth note" --goal "locate the auth flow note" \\
  -- search content --query "authentication flow" --limit 5

# 3. read the top hit (search gave a path, not the text)
nexus use \\
  --workspace research --session auth-summary \\
  --memory "found Projects/Auth/flow.md; reading it" --goal "read the auth flow note" \\
  -- content read --path Projects/Auth/flow.md --start-line 1

# 4. edit — anchor on exact text pulled from the read
nexus use \\
  --workspace research --session auth-summary \\
  --memory "have the body; inserting a summary" --goal "replace the Summary section" \\
  -- content replace --path Projects/Auth/flow.md \\
  --start "## Summary" --end "## Details" \\
  --content "## Summary\\n\\nOAuth2 + PKCE; tokens rotate hourly.\\n\\n"

# 5. checkpoint (create-state needs name + context + task + file/step arrays)
nexus use \\
  --workspace research --session auth-summary \\
  --memory "summary written to flow.md" --goal "checkpoint the finished edit" \\
  -- memory create-state --name auth-summary-done \\
  --conversation-context "summarized the auth flow note into a Summary section" \\
  --active-task "add a summary to flow.md" \\
  --active-files "[Projects/Auth/flow.md]" \\
  --next-steps "[review the summary with the team]"
\`\`\`

## Pitfalls

- **Editing from a search hit without reading** — the hit is a location; you'll
  guess the body wrong. Always \`content read\` first.
- **\`content replace\` with line numbers** — it wants anchor *text* in
  \`start\`/\`end\`. Copy the anchors verbatim from the read.
- **Answering a question from \`{path, score}\`** — read the note; don't fabricate
  from the ranking.
- **Losing trace scope** — pass \`--workspace\` on every call, not just the load.
- **Writing outside the vault** — \`..\`/\`~\`/absolute paths are rejected; keep
  paths vault-relative.
`,
};
