/**
 * MessageRepository Unit Tests
 *
 * Tests for the convertAlternativesToEvent helper method.
 * Bug #5: Alternative messages in branches were losing tool call metadata
 * during JSONL serialization because convertAlternativesToEvent was not
 * persisting the extended properties (name, parameters, result, success,
 * error, executionTime).
 *
 * Since MessageRepository is a concrete class with infrastructure dependencies
 * (SQLite, JSONL writer), we test the conversion logic by extracting and
 * verifying the serialization pattern directly.
 */

import {
  createAlternativeMessage,
  createCompletedToolCall,
  createFailedToolCall,
  createIncompleteToolCall
} from '../fixtures/chatBugs';
import type { AlternativeMessageEvent } from '../../src/database/interfaces/StorageEvents';
import type { MessageEvent, MessageUpdatedEvent } from '../../src/database/interfaces/StorageEvents';
import { MessageRepository } from '../../src/database/repositories/MessageRepository';
import type { RepositoryDependencies } from '../../src/database/repositories/base/BaseRepository';
import { ConversationEventApplier } from '../../src/database/sync/ConversationEventApplier';
import { convertToLegacyConversation } from '../../src/services/helpers/ConversationTypeConverters';
import { AnthropicContextBuilder } from '../../src/services/chat/builders/AnthropicContextBuilder';

type TestToolCall = {
  id: string;
  type?: string;
  function: { name: string; arguments: string };
  name?: string;
  parameters?: Record<string, unknown>;
  result?: unknown;
  success?: boolean;
  error?: string;
  executionTime?: number;
};

// Only SQL/JSONL I/O is replaced: the repository serializes the real write and
// the real applier replays it. Rows come from emitted SQL, never preset metadata.
function createMessagePersistenceHarness() {
  const rows = new Map<string, Record<string, unknown>>();
  const events: Array<MessageEvent | MessageUpdatedEvent> = [];
  const sqliteCache = {
    queryOne: jest.fn(async (sql: string, params: unknown[]) => {
      if (sql.includes('MAX(sequenceNumber)')) return { maxSeq: -1 };
      return rows.get(String(params[0])) ?? null;
    }),
    run: jest.fn(async (sql: string, params: unknown[]) => {
      const insert = /INSERT(?: OR REPLACE)? INTO messages\s*\(([^)]+)\)/.exec(sql);
      if (!insert) {
        const update = /UPDATE messages SET ([\s\S]+) WHERE id = \?/.exec(sql);
        if (!update) return;
        const row = rows.get(String(params[params.length - 1]));
        if (!row) return;
        update[1].split(',').forEach((clause, index) => {
          const column = clause.trim().split(' = ')[0];
          row[column] = params[index];
        });
        return;
      }
      const columns = insert[1].split(',').map(column => column.trim());
      expect(params).toHaveLength(columns.length);
      const row = Object.fromEntries(columns.map((column, index) => [column, params[index]]));
      rows.set(String(row.id), row);
    })
  };
  const deps = {
    sqliteCache,
    jsonlWriter: {
      appendEvent: jest.fn(async (_path: string, event: Omit<MessageEvent | MessageUpdatedEvent, 'id' | 'timestamp' | 'deviceId'>) => {
        const stored: MessageEvent | MessageUpdatedEvent = JSON.parse(JSON.stringify({
          ...event, id: 'event-1', timestamp: 123456, deviceId: 'device-1'
        }));
        events.push(stored);
        return stored;
      })
    },
    queryCache: { invalidateByType: jest.fn() }
  };
  return { repo: new MessageRepository(deps as unknown as RepositoryDependencies), sqliteCache, rows, events };
}

describe('MessageRepository message metadata persistence', () => {
  const metadata = {
    type: 'subagent_result', remoteJobId: 'job-1', branchId: 'branch-1',
    remoteTargetId: 'hermes-1', runId: 'run-1', isAutoGenerated: true,
    success: true, details: { source: 'remote', tags: ['durable'] }
  };

  it('preserves metadata in the source event, immediate cache read and completion observer', async () => {
    const { repo, events } = createMessagePersistenceHarness();
    const completed = jest.fn();
    repo.onMessageComplete(completed);

    await repo.addMessage('parent-1', {
      id: 'remote-result-1', role: 'assistant', content: 'Remote reply', timestamp: 123456, metadata
    });

    expect(events[0].data).toEqual(expect.objectContaining({ metadata }));
    expect(await repo.getById('remote-result-1')).toEqual(expect.objectContaining({ metadata }));
    expect(completed).toHaveBeenCalledWith(expect.objectContaining({ metadata }));
  });

  it('restores remote result identity from the emitted JSONL event into an empty cache', async () => {
    const original = createMessagePersistenceHarness();
    await original.repo.addMessage('parent-1', {
      id: 'remote-result-1', role: 'assistant', content: 'Remote reply', timestamp: 123456, metadata
    });
    const rebuilt = createMessagePersistenceHarness();
    const applier = new ConversationEventApplier(rebuilt.sqliteCache);
    await applier.apply(original.events[0]);

    expect(await rebuilt.repo.getById('remote-result-1')).toEqual(expect.objectContaining({
      id: 'remote-result-1', conversationId: 'parent-1', content: 'Remote reply', metadata
    }));
  });

  it('continues to add ordinary messages without metadata', async () => {
    const { repo, rows } = createMessagePersistenceHarness();
    await repo.addMessage('parent-1', {
      id: 'ordinary-1', role: 'user', content: 'Hello', timestamp: 123456
    });
    expect(rows.get('ordinary-1')?.metadataJson).toBeNull();
    expect((await repo.getById('ordinary-1'))?.metadata).toBeUndefined();
  });

  it('persists a metadata-only update and replays it after cache rebuild', async () => {
    const original = createMessagePersistenceHarness();
    await original.repo.addMessage('parent-1', {
      id: 'assistant-1', role: 'assistant', content: 'Reply', timestamp: 123456
    });
    const usageMetadata = { latestResponseUsage: { promptTokens: 40, completionTokens: 5 },
      providerData: { raw: ['preserve', 1] } };
    await original.repo.update('assistant-1', { metadata: usageMetadata });

    expect((await original.repo.getById('assistant-1'))?.metadata).toEqual(usageMetadata);
    expect(original.events[1]).toMatchObject({ type: 'message_updated', data: { metadata: usageMetadata } });

    const rebuilt = createMessagePersistenceHarness();
    const applier = new ConversationEventApplier(rebuilt.sqliteCache);
    for (const event of original.events) await applier.apply(event);
    expect((await rebuilt.repo.getById('assistant-1'))?.metadata).toEqual(usageMetadata);
  });

  it('leaves metadata untouched when omitted and clears old Anthropic replay on explicit null after rebuild', async () => {
    const original = createMessagePersistenceHarness();
    await original.repo.addMessage('parent-1', {
      id: 'assistant-1', role: 'assistant', content: 'OLD ANSWER', timestamp: 123456,
      metadata: { anthropicResponses: [{ content: [{ type: 'text', text: 'OLD ANSWER' }], toolCallIds: [], contentEndOffset: 10 }] }
    });
    await original.repo.update('assistant-1', { content: 'NEW ANSWER is longer' });
    expect((await original.repo.getById('assistant-1'))?.metadata)
      .toEqual({ anthropicResponses: [{ content: [{ type: 'text', text: 'OLD ANSWER' }], toolCallIds: [], contentEndOffset: 10 }] });
    await original.repo.update('assistant-1', { metadata: null });
    expect((await original.repo.getById('assistant-1'))?.metadata).toBeUndefined();

    const rebuilt = createMessagePersistenceHarness();
    const applier = new ConversationEventApplier(rebuilt.sqliteCache);
    for (const event of original.events) await applier.apply(event);
    const reloaded = await rebuilt.repo.getById('assistant-1');
    expect(reloaded?.metadata).toBeUndefined();
    const conversation = convertToLegacyConversation({
      id: 'parent-1', title: 'Test', created: 1, updated: 1, vaultName: 'test', messageCount: 1,
    }, [reloaded!]);
    const replay = new AnthropicContextBuilder().buildContext(conversation);
    expect(replay).toEqual([{ role: 'assistant', content: 'NEW ANSWER is longer' }]);
    expect(JSON.stringify(replay)).not.toContain('OLD ANSWER');
  });
});

/**
 * Replicate the convertAlternativesToEvent logic from MessageRepository
 * for isolated unit testing without needing SQLite/JSONL infrastructure.
 *
 * This mirrors MessageRepository.ts lines 380-403 exactly.
 */
function convertAlternativesToEvent(
  alternatives?: Array<{
    id: string;
    content: string | null;
    timestamp: number;
    toolCalls?: TestToolCall[];
    reasoning?: string;
    state?: string;
  }>
): AlternativeMessageEvent[] | undefined {
  if (!alternatives || alternatives.length === 0) {
    return undefined;
  }
  return alternatives.map(alt => ({
    id: alt.id,
    content: alt.content,
    timestamp: alt.timestamp,
    tool_calls: alt.toolCalls?.map((tc: TestToolCall) => ({
      id: tc.id,
      type: tc.type || 'function',
      function: tc.function,
      // Extended properties for tool bubble reconstruction
      name: tc.name,
      parameters: tc.parameters,
      result: tc.result,
      success: tc.success,
      error: tc.error,
      executionTime: tc.executionTime
    })),
    reasoning: alt.reasoning,
    state: alt.state
  }));
}

function expectDefined<T>(value: T | null | undefined): T {
  expect(value).toBeDefined();
  return value as T;
}

describe('MessageRepository convertAlternativesToEvent', () => {
  // ==========================================================================
  // Basic conversion
  // ==========================================================================

  describe('basic conversion', () => {
    it('should return undefined for undefined input', () => {
      const result = convertAlternativesToEvent(undefined);
      expect(result).toBeUndefined();
    });

    it('should return undefined for empty array', () => {
      const result = convertAlternativesToEvent([]);
      expect(result).toBeUndefined();
    });

    it('should convert a single alternative without tool calls', () => {
      const alt = createAlternativeMessage({ toolCalls: undefined });
      const result = convertAlternativesToEvent([alt]);

      const event = expectDefined(result)[0];
      expect(result).toBeDefined();
      expect(expectDefined(result).length).toBe(1);
      expect(event.id).toBe(alt.id);
      expect(event.content).toBe(alt.content);
      expect(event.timestamp).toBe(alt.timestamp);
      expect(event.tool_calls).toBeUndefined();
      expect(event.reasoning).toBe(alt.reasoning);
      expect(event.state).toBe(alt.state);
    });
  });

  // ==========================================================================
  // Tool call metadata persistence (Bug #5 core fix)
  // ==========================================================================

  describe('tool call metadata persistence (Bug #5)', () => {
    it('should persist all extended tool call properties', () => {
      const toolCall = createCompletedToolCall({
        id: 'tc_full',
        name: 'searchContent',
        parameters: { query: 'test' },
        result: { matches: ['a.md'] },
        success: true,
        error: undefined,
        executionTime: 200
      });

      const alt = createAlternativeMessage({
        toolCalls: [toolCall]
      });

      const result = convertAlternativesToEvent([alt]);

      const eventToolCall = expectDefined(expectDefined(result)[0].tool_calls)[0];

      // Core OpenAI format fields
      expect(eventToolCall.id).toBe('tc_full');
      expect(eventToolCall.type).toBe('function');
      expect(eventToolCall.function).toEqual(toolCall.function);

      // Extended fields (Bug #5 fix - these were previously missing)
      expect(eventToolCall.name).toBe('searchContent');
      expect(eventToolCall.parameters).toEqual({ query: 'test' });
      expect(eventToolCall.result).toEqual({ matches: ['a.md'] });
      expect(eventToolCall.success).toBe(true);
      expect(eventToolCall.executionTime).toBe(200);
    });

    it('should persist error field on failed tool calls', () => {
      const toolCall = createFailedToolCall({
        id: 'tc_err',
        error: 'File not found',
        success: false
      });

      const alt = createAlternativeMessage({ toolCalls: [toolCall] });
      const result = convertAlternativesToEvent([alt]);

      const eventToolCall = expectDefined(expectDefined(result)[0].tool_calls)[0];
      expect(eventToolCall.error).toBe('File not found');
      expect(eventToolCall.success).toBe(false);
    });

    it('should handle multiple tool calls per alternative', () => {
      const tc1 = createCompletedToolCall({ id: 'tc_1', result: 'result1' });
      const tc2 = createCompletedToolCall({ id: 'tc_2', result: 'result2' });
      const tc3 = createFailedToolCall({ id: 'tc_3' });

      const alt = createAlternativeMessage({ toolCalls: [tc1, tc2, tc3] });
      const result = convertAlternativesToEvent([alt]);

      const toolCalls = expectDefined(expectDefined(result)[0].tool_calls);
      expect(toolCalls.length).toBe(3);
      expect(toolCalls.map(tc => tc.id)).toEqual(['tc_1', 'tc_2', 'tc_3']);
    });
  });

  // ==========================================================================
  // Round-trip fidelity
  // ==========================================================================

  describe('round-trip fidelity', () => {
    it('should produce JSON that can be parsed back with full fidelity', () => {
      const toolCall = createCompletedToolCall({
        id: 'tc_round',
        name: 'myTool',
        parameters: { nested: { key: 'value' } },
        result: { complex: [1, 2, 3] },
        success: true,
        executionTime: 100
      });

      const alt = createAlternativeMessage({
        id: 'alt_round',
        content: 'Round trip content',
        toolCalls: [toolCall],
        reasoning: 'Some reasoning',
        state: 'complete'
      });

      // Serialize
      const events = convertAlternativesToEvent([alt]);
      const json = JSON.stringify(events);

      // Deserialize
      const parsed: AlternativeMessageEvent[] = JSON.parse(json);

      expect(parsed.length).toBe(1);
      expect(parsed[0].id).toBe('alt_round');
      expect(parsed[0].content).toBe('Round trip content');
      expect(parsed[0].reasoning).toBe('Some reasoning');
      expect(parsed[0].state).toBe('complete');

      const parsedTc = expectDefined(parsed[0].tool_calls)[0];
      expect(parsedTc.id).toBe('tc_round');
      expect(parsedTc.name).toBe('myTool');
      expect(parsedTc.parameters).toEqual({ nested: { key: 'value' } });
      expect(parsedTc.result).toEqual({ complex: [1, 2, 3] });
      expect(parsedTc.success).toBe(true);
      expect(parsedTc.executionTime).toBe(100);
    });

    it('should default type to function when not set', () => {
      const toolCall = createIncompleteToolCall({
        id: 'tc_notype',
        type: undefined
      });

      const alt = createAlternativeMessage({ toolCalls: [toolCall] });
      const result = convertAlternativesToEvent([alt]);

      expect(expectDefined(expectDefined(result)[0].tool_calls)[0].type).toBe('function');
    });
  });

  // ==========================================================================
  // Multiple alternatives
  // ==========================================================================

  describe('multiple alternatives', () => {
    it('should convert multiple alternatives correctly', () => {
      const alt1 = createAlternativeMessage({
        id: 'alt_1',
        content: 'First alternative',
        toolCalls: [createCompletedToolCall({ id: 'tc_a1' })]
      });
      const alt2 = createAlternativeMessage({
        id: 'alt_2',
        content: 'Second alternative',
        toolCalls: undefined
      });

      const result = convertAlternativesToEvent([alt1, alt2]);

      expect(expectDefined(result).length).toBe(2);
      expect(expectDefined(result)[0].id).toBe('alt_1');
      expect(expectDefined(expectDefined(result)[0].tool_calls).length).toBe(1);
      expect(expectDefined(result)[1].id).toBe('alt_2');
      expect(expectDefined(result)[1].tool_calls).toBeUndefined();
    });
  });
});
